name: cicoclip
channels:
  - simpleitk
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.6
  - numpy
  - pandas
  - pip
  - pyqt=5.6.0
  - scikit-learn
  - scipy
  - nibabel
  - pydicom
  - vtk
  - pip:
    - matplotlib
    - simpleitk
